### ISSUE TITLE
Handling `undefined` objects/arrays

### ISSUE THREAD

**Issue by ctate** [brandonhorst/confine#1]
Hi - I've tried a lot of validators for Node.js and this appears to be the most robust. The only issue I'm running into is that `undefined` objects and arrays fail validation since they are normalized as `{}` and `[]`. Is it possible to keep them as `undefined` if an `undefined` object/array is passed (like strings)? Right now, it behaves like it's a required field (which might be another good option to have down the road).

Please let me know. I can also submit a PR if you'd like. Thanks for your help and consideration!

**Comment by brandonhorst** [comment]
My answer is quite a read. Sorry.

The goal of `confine` is not necessarily to do validation. The primarily goal is normalization - to take something, extract whatever data fits the schema, force it into a reliable form. It's not really intented to validate, say, form entries.

The reason that `confine.normalize(undefined, objectSchema)` returns an object is so that it can fill nested defaults.

``` js
var schema = {
  type: 'object',
  properties: {
    myStr: {type: 'string', default: 'test'}
  }
}

confine.normalize(undefined, schema)
confine.normalize({}, schema)
confine.normalize(3, schema)
// {myStr: 'test'}
```

That way, a consumer can _always_ always access `normalizedObj.myStr.length` confident that they will not get a `cannot access property (myStr|length) of undefined` error. If `normalize(undefined, schema)` returned `undefined` by default, then the only way to make that guarantee would be to specify the defaults _twice_, like so:

``` js
var schema = {
  type: 'object',
  properties: {
    myStr: {type: 'string', default: 'test'} // for handling {}
  },
  default: {myStr: 'test'} // for handling undefined|3
}
confine.normalize(undefined, schema)
confine.normalize({}, schema)
confine.normalize(3, schema)
// {myStr: 'test'}
```

That's not a great solution.

I think that the right way to handle this would be to:
- change the name of the current `validate` to `isNormalized`
- make a new universal property called `required`
- add a validateSchema check - if `schema.required && _.isUndefined(isNormalized(undefined, schema))`, the schema is invalid
  - otherwise `validate(normalize(x, schema))` would return `false` for `_.isUndefined(x)`, which shouldn't happen
  - therefore, every schema that is `required` must either be of type `object`, `array` or `null`, or have a `default`. No way around that without breaking normalization
- make a new method called `validate` which behaves something like this (I may have missed some edge cases):

``` js
Confine.prototype.validate = function (obj, schema, manager) {
  if (_.isUndefined) return !schema.required

  return this.types[schema.type].validate(obj, schema, manager)
}
```

This would be a major version change of course.

If you can make sense of all that, how that sound?

**Comment by ctate** [comment]
Thank you very much for the explanation. That makes perfect sense and I completely understand the goal and the importance of normalizing data. I don't want to change that so I'll do the validation myself and use this module when I need to normalize data. I really appreciate the time you took to provide an excellent explanation and create such an awesome module. Thanks again!
